[package]
name = "wechat-saver"
version = "0.1.0"
edition = "2021"

[dependencies]
silkv3-rs = { path = "../silkv3-rs" }
tar = "0.4.42"
md-5 = "0.10.6"
rusqlite = {version = "0.32.1",features = ["sqlcipher"]}
hex = "0.4.3"